# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1p8xn86TsqCFRN7uFlaTodI9Q2_Csm8
"""

import pandas as pd
teacher=pd.DataFrame({
    "FISH":["Qadamova Zulayho", "Karimov S", "Ibragimov N", "Azizov I", "Xusanova M", "Raxmonov O" ],
    "Fani":["Sun'iy intelekt asoslari", "Sun'iy intelekt asoslari", "Bugalteriya hisobi", "Bugalteriya hisobi", "Kiberxavfsizlik asoslari", "Kiberxavfsizlik asoslari" ],
    "Mashg'ulot turi" :["amaliy", "ma'ruza", "amaliy", "ma'ruza", "amaliy", "ma'ruza"],
    "Kafedrasi":["Axborot texnologiyalari","Axborot texnologiyalari", "Kasbiy ta'lim", "Kasbiy ta'lim", "Kiberxavfsizlik", "Kiberxavfsizlik"]
    })
print(teacher)

teacher.to_excel("660-guruh teacher's.xlsx")